import 'package:doctorappointment/models/doctor_model.dart';

List<Doctor> doctors = [
  Doctor(
    id: '0',
    name: 'Jenny Roy',
    image: 'assets/images/doctors/doctor1.png',
    department: 'Cardiologist',
    price: 350,
    rate: 4.6,
    description:
        "Dr. Jenny Roy is the top most cardiologist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1078,
  ),
  Doctor(
    id: '1',
    name: 'Edward George',
    image: 'assets/images/doctors/doctor2.png',
    department: 'Cardiologist',
    price: 340,
    rate: 3.5,
    description:
        "Dr. Edward George is the top most cardiologist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '2',
    name: 'Charles Burton',
    image: 'assets/images/doctors/doctor3.png',
    department: 'Cardiologist',
    price: 350,
    rate: 4.5,
    description:
        "Dr. Charles Burton is the top most cardiologist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '3',
    name: 'Mark Hall',
    image: 'assets/images/doctors/doctor4.png',
    department: 'Cardiologist',
    price: 350,
    rate: 3.9,
    description:
        "Dr. Mark Hall is the top most cardiologist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '4',
    name: 'Peter Leavitt',
    image: 'assets/images/doctors/doctor5.png',
    department: 'Cardiologist',
    price: 350,
    rate: 4.3,
    description:
        "Dr. Peter Leavitt is the top most cardiologist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '5',
    name: 'Jeremy Stone',
    image: 'assets/images/doctors/doctor6.png',
    department: 'Cardiologist',
    price: 350,
    rate: 4.2,
    description:
        "Dr. Jeremy Stone is the top most cardiologist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '6',
    name: 'Martin Arrowsmith',
    image: 'assets/images/doctors/doctor7.png',
    department: 'Cardiologist',
    price: 350,
    rate: 4.1,
    description:
        "Dr. Martin Arrowsmith is the top most cardiologist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '7',
    name: 'Jefferson Jefferson',
    image: 'assets/images/doctors/doctor8.png',
    department: 'Orthopedic',
    price: 350,
    rate: 5.0,
    description:
        "Dr. Jefferson Jefferson is the top most Orthopedic\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '8',
    name: 'Timothy Flyte',
    image: 'assets/images/doctors/doctor9.png',
    department: 'Orthopedic',
    price: 400,
    rate: 5.0,
    description:
        "Dr. Timothy Flyte is the top most Orthopedic\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '9',
    name: 'Jennifer Paige',
    image: 'assets/images/doctors/doctor10.png',
    department: 'Orthopedic',
    price: 330,
    rate: 4.5,
    description:
        "Dr. Jennifer Paige is the top most Orthopedic\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '10',
    name: 'Bernard Rieux',
    image: 'assets/images/doctors/doctor11.png',
    department: 'Orthopedic',
    price: 350,
    rate: 4.0,
    description:
        "Dr. Bernard Rieux is the top most Orthopedic\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '11',
    name: 'Henry Higgins',
    image: 'assets/images/doctors/doctor12.png',
    department: 'Orthopedic',
    price: 350,
    rate: 4.0,
    description:
        "Dr. Henry Higgins is the top most Orthopedic\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '12',
    name: 'Hastie Lanyon',
    image: 'assets/images/doctors/doctor13.png',
    department: 'Orthopedic',
    price: 380,
    rate: 4.6,
    description:
        "Dr. Hastie Lanyon is the top most Orthopedic\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '13',
    name: 'Montgomery Montgomery',
    image: 'assets/images/doctors/doctor14.png',
    department: 'Orthopedic',
    price: 300,
    rate: 3.5,
    description:
        "Dr. Montgomery Montgomery is the top most Orthopedic\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 6,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '14',
    name: 'Leonard Doull',
    image: 'assets/images/doctors/doctor15.png',
    department: 'Dentist',
    price: 300,
    rate: 4.2,
    description:
        "Dr. Leonard Doull is the top most Dentist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 5,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '15',
    name: 'Dick Diver',
    image: 'assets/images/doctors/doctor16.png',
    department: 'Dentist',
    price: 330,
    rate: 4.3,
    description:
        "Dr. Dick Diver is the top most Dentist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 5,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '16',
    name: 'John Quimper',
    image: 'assets/images/doctors/doctor17.png',
    department: 'Dentist',
    price: 300,
    rate: 4.2,
    description:
        "Dr. John Quimper is the top most Dentist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 5,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '17',
    name: 'Rumack',
    image: 'assets/images/doctors/doctor18.png',
    department: 'Dentist',
    price: 300,
    rate: 4.2,
    description:
        "Dr. Rumack is the top most Dentist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 5,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '18',
    name: 'Leo Bain',
    image: 'assets/images/doctors/doctor19.png',
    department: 'Dentist',
    price: 300,
    rate: 4.2,
    description:
        "Dr. Leo Bain is the top most Dentist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 5,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
  Doctor(
    id: '19',
    name: 'Martin Arrowsmith',
    image: 'assets/images/doctors/doctor20.png',
    department: 'Dentist',
    price: 400,
    rate: 5.0,
    description:
        "Dr. Martin Arrowsmith is the top most Dentist\n specialist in Dhaka Medical College hospital\n at Dhaka.He achived several award for his\n wonderful contribution in her own field.He is\n available for private consultation.",
    experienceYears: 5,
    hospitalName: 'Dhaka Medical College Hospital',
    patientsCount: 1100,
  ),
];
